### PR TITLE
mod by dkxce commit, v1.1.4

### PR DESCRIPTION
**Pull request by dkxce**
Add support to restore windows from tray popup menu

### CODE REVIEW

**Comment by fcFn** [comment]
Hello @dkxce, and thank you for your contribution! 😊 

That's quite a lot of changes and will take me a while to go over with. I'll keep you posted.

**Comment by fcFn** [comment]
Hello @dkxce, and thank you for your contribution! 😊 

That's quite a lot of changes and will take me a while to go over with. I'll keep you posted.

**Comment by dkxce** [comment]
You can download _rls version at
https://github.com/dkxce/traymond/releases/tag/v2.0.3

**Comment by dkxce** [comment]
You can download _rls version at
https://github.com/dkxce/traymond/releases/tag/v2.0.3

**Pull request closed without merging**
