### PR TITLE
 Enable building in Visual Studio with Project file 

### PR DESCRIPTION
**Pull request by tylerszabo**
- Create `proj` & `sln` files for Visual Studio
- Fix compiler warnings

### CODE REVIEW

**Comment by tylerszabo** [comment]
I wanted to take advantage of IntelliSense (it might make this more consumable to be able to build in VS) so I imported it and tuned the project file to remove some cruft (in VS, because VS is picky about how proj files are set up).

Since your `CONTRIBUTING.md` was inviting changes I thought I'd offer to share back if you're interested. :)

**Comment by fcFn** [comment]
@tylerszabo Thanks a lot!

Could you clean up the .gitignore a bit, please? It looks really bloated as there is a lot of stuff that doesn't belong there (e. g. F# Make, Rider). I'd do that myself, but you probably know better what really has to be ignored when developing and building the app in VS.

**Comment by tylerszabo** [comment]
I sure can; but I'd like to first explain my reason for picking this huge one. The segment is command and reasonably standard. [Here](
https://github.com/github/gitignore/blob/master/VisualStudio.gitignore so it's a trade-off between using something standard and )'s where it's maintained (that comment is in the file). Thus I think there's value in the verbosity (so to speak) when it's to avoid being different.

With that said, I'm happy to remove it or better annotate that custom ignores should be added above, and the rest of the file is a clone of the common one.

**Comment by fcFn** [comment]
Thanks for pointing that out! I didn't notice the link in the file. I guess that's OK then. Let's merge!

I'm really excited that this project got its first contributor by the way!

**Pull request merged**
